name: Scan API with CodeSent

on:
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan with CodeSent
        uses: codesentio/codesent-scan-action@v1.1-alpha4
        with:
          api-key: ${{ secrets.CODESENT_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}